### ISSUE TITLE
Trino exception in dev of failed fetching statistics for table

### ISSUE THREAD

**Issue by mutambaraf** [UserOfficeProject/user-office-project-issue-tracker#991] opened 2024-01-26 13:21 UTC
### What is the problem and why is it a problem
Trino is throwing exception of failed fetching statistics for table public.proposal_table_view  for columns proposal_pk and proposal_status_name. This looks like it is not affecting the results of the query in the reporting tool.

### Steps to reproduce (if it's a bug).
Run this report [ISIS Proposals submitted by round](https://devoffice.facilities.rl.ac.uk/reporting/SQLView.aspx?category=isis-proposals&query=isis-proposals-submitted-by-round) and check trino pod logs in dev cluster.

`
2024-01-26T13:07:36.091Z        ERROR   Query-20240126_130735_00008_r5mwu-582   io.trino.cost.CachingStatsProvider      Error occurred when computing stats for query 20240126_130735_00008_r5mwu
io.trino.spi.TrinoException: Failed fetching statistics for table: public.proposal_table_view public.proposal_table_view columns=[proposal_pk:integer:int4, proposal_status_name:varchar(100):varchar]
`

**Comment by simonfernandes** [comment] 2024-01-30 12:50
Looks like this was caused by our Postgres upgrade and [fixed in Trino version 414](https://github.com/trinodb/trino/issues/17061) (437 is the latest and we are on 410).



The effect of this seems to be:

> Trino uses statistics about tables and columns to optimize query execution plans. When executing a query, Trino may fetch statistics to help it make better decisions about how to execute the query efficiently.

**Closed as completed** 2024-02-27 15:37 UTC
Labels: area: uop/stfc
