### ISSUE TITLE
As a developer, I would like ESLint to be ran on all PRs, to avoid reviewing style issues

### ISSUE THREAD

**Issue by TickleThePanda** [UserOfficeProject/user-office-project-issue-tracker#342] opened 2022-03-02 15:12 UTC
ESLint isn't ran on PRs currently, it should be

**Comment by mr-field** [comment] 2022-03-04 11:16
Closing as duplicate of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/234. I'll change the milestone of the other issue to match this one.

**Closed by mr-field** 2022-03-04 11:16 UTC
Labels: origin: project, triage: duplicate, area: uop/stfc
