### ISSUE TITLE
Attempting to submit an invalid date via the "Add A Grant" control results in a hang

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#719] opened 2022-10-06 14:38 UTC
If a user attempts to manually enter an invalid date via the Research Grants -> Add A Grant form, they get a spinning blue wheel and no opportunity to cancel. They must back out of the form. No explanation is given.
This affects User Role but likely all others
Validation needs to detect badly formatted (manually entered) dates and handle them or manual entry needs to be removed.

![image](https://user-images.githubusercontent.com/75302934/194341970-45c5fbcc-2bc3-4ed8-a161-0d09457bcfec.png)

**Comment by TickleThePanda** [comment] 2022-10-06 16:21
I think this is a duplicate of the more general https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/689

**Closed by TickleThePanda** 2022-10-06 16:21 UTC
Labels: type: bug, area: uop/stfc
