### ISSUE TITLE
Update Auth Searchable Description for FAPs 

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#968] opened 2023-11-16 16:41 UTC
Refs: #961

Users cannot be assigned to FAP roles (chair, secretary, reviewer) if they are not marked as searchable in the User DB. We should update the description of the searchability functionality in Auth to explain to users that they need to opt in to it to be added to FAPs.

**Comment by RasmiaKulan** [comment] 2023-12-12 13:12
The issue is being worked on in Users repo

**Comment by TCMeldrum** [comment] 2024-01-30 14:59
Closed by: https://github.com/isisbusapps/Users/pull/3877

**Closed as completed by TCMeldrum** 2024-01-30 14:59 UTC
Labels: status: new, area: uop/stfc, area: uop/stfc/reviews-allocations
