### ISSUE TITLE
getGenericTemplatesWithProposalData has a 77% error rate on call deadline

### ISSUE THREAD

**Issue by TCMeldrum** [UserOfficeProject/user-office-project-issue-tracker#1259] opened 2024-11-21 13:56 UTC

**Comment by ACLay** [comment] 2024-11-29 14:21
This is the chart of this query's error rate between 9am October 13th - 5pm October 18th, the week with the call deadline:
![image](https://github.com/user-attachments/assets/15bfc81c-13ff-4987-ad62-5d6c1f75748f)

And in our log server, a search for `getGenericTemplatesWithProposalData` in the same time range gives this plot of logs, which from a brief glance all seem to be error records for failed user office web service calls and be using the same generic templates filter `{"questionId":"generic_template_1634227264949"}`:
![image](https://github.com/user-attachments/assets/2b46a031-142f-415b-8224-9347bd80ec44)

Looking at the source for the graphql query, we seem to be fetching [every response for that generic template question](https://github.com/UserOfficeProject/user-office-core/blob/8556e52dd2958a76b0540801357fc0e700b1eadb/apps/backend/src/queries/GenericTemplateQueries.ts#L47), and then filtering them in code to determine whether the user is allowed to see them. That filtering takes the proposalPk for each response and checks if the user is permitted to view that proposal, ultimately using what seems like the [same code](https://github.com/UserOfficeProject/user-office-core/blob/8556e52dd2958a76b0540801357fc0e700b1eadb/apps/backend/src/auth/ProposalAuthorization.ts#L191) identified as the cause of slowdown in #1193

**Comment by ACLay** [comment] 2024-11-29 16:07
This is the same query that was flagged for optimisation in #1193.

**Comment by ACLay** [comment] 2024-11-29 16:20
Since I'm pretty sure of the cause now, the optimisations for that issue should be the solution to preventing this happening again. Gonna close this since the remaining work is basically a duplicate and already in progress.

**Closed as completed by ACLay** 2024-11-29 16:20 UTC
