### ISSUE TITLE
Proposals don't delete cleanly

### ISSUE THREAD

**Issue by simonfernandes** [UserOfficeProject/user-office-project-issue-tracker#928] opened 2023-10-09 10:26 UTC
Proposals do delete without user error, but in the backend we see this each time: 

> Ignored value{"message":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *; - insert or update on table \"proposal_events\" violates foreign key constraint \"proposal_events_proposal_id_fkey\"","error":{"length":302,"name":"error","severity":"ERROR","code":"23503","detail":"Key (proposal_pk)=(15130) is not present in table \"proposals\".","schema":"public","table":"proposal_events","constraint":"proposal_events_proposal_id_fkey","file":"ri_triggers.c","line":"2783","routine":"ri_ReportViolation"},"obj":{"__knexUid":"__knexUid8304","__knexTxId":"__knexUid8304","method":"raw","sql":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *;","bindings":[true,15130],"options":{},"__knexQueryUid":"ndYchHHQknr7je8lyyH8r"},"QueryName":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *;"}

### What is the problem and why is it a problem

It looks like part of the deletion process fails, which is inserting a deleted = true to the proposal_events table.

### Steps to reproduce (if it's a bug).

Delete a proposal

**Comment by simonfernandes** [comment] 2023-10-09 10:49
Some research: 

1. The proposal row from the `proposals` table is deleted successfully
2. Corresponding row in `proposal_events` is also deleted successfully (cascade delete)
3. Query error trying to insert a new row with `deleted = true` in the `proposal_events` table because it's trying to reference the deleted `proposals` primary key


We might need to either not delete the `proposals` row, or accept that a `proposal_events` row deletes with the proposal. We still have a record that the proposal was deleted in the `event_log` table.

**Comment by simonfernandes** [comment] 2023-10-18 09:45
Sprint planning notes:

We don't mind if users delete their proposal and there's no record, but it's more problematic if a user officer deletes. Possible solution is to restrict who is classed as a user officer (e.g. only Emma) and lower others to scientist role.

Also we should ensure there's a confirmation on delete button pressed.

**Comment by Cat-Lucifer** [comment] 2023-10-18 11:05
@simonfernandes Staff to change from `User Officer` to `Experimental Scientist` role in the new proposal system:

Emma Roberts
Kerry Larman
Lisa Wiltshire
Marie Richer
Ellie Samworth

**Comment by simonfernandes** [comment] 2023-10-18 12:56
@Cat-Lucifer Sorry, I don't think this is actually possible at the moment with the way things work. We map each person's Active Directory group to system role. If we remove the User Office Active Directory group from your team members then it's going to affect permissions in other systems.

**Comment by Cat-Lucifer** [comment] 2023-10-19 07:31
@simonfernandes Okay, thanks for looking into it.  My team don't really use the new system, so hopefully there's minimal chance of them deleting a proposal by accident.

Interestingly (and timely), I was asked by a user to delete a duplicate proposal of theirs this morning.  I used the delete option and the system already has an additional pop up that asks along the lines of "are you sure" before you can confirm deletion.

**Comment by simonfernandes** [comment] 2023-11-15 14:01
@martin-trajanovski I think we also experienced the same problem you described 😀

**Comment by bashanlam** [comment] 2024-06-13 09:36
This issue caused by the proposal_deleted event in the workflow engine was resolved by the fix in https://github.com/UserOfficeProject/user-office-core/pull/623.

**Closed as completed by bashanlam** 2024-06-13 09:36 UTC
Labels: type: bug, area: uop/stfc
