### ISSUE TITLE
Add an "instrument requested" line to the auto-email sent upon proposal submission

### ISSUE THREAD

**Issue by georgeflecknell** [UserOfficeProject/user-office-project-issue-tracker#710] opened 2022-09-16 12:27 UTC
Currently the User Office receive the following upon proposal submission. Emma Gozzard has requested addition of a line stating the instrument requested.

"
Subject: A Rapid Access proposal has been submitted

A Rapid Access proposal has been submitted.
The proposal details are as follows:
Proposal Title: XXXXXX
Proposal Reference No: 2200354
Principal Investigator: XXXXXXXX
Co Investigator(s): XXXXXXX
Please do not reply to this e-mail, this is an automated message.
"

This change is requested as soon as is possible but not with high importance.

**Comment by simonfernandes** [comment] 2022-09-20 12:03
@georgeflecknell 

I think this is a duplicate of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/639, if this just applies to Rapid. Feel free to re-open and add extra information if it's not

**Comment by simonfernandes** [comment] 2022-09-20 12:04
__

**Closed** 2022-09-20 12:04 UTC
Labels: type: feature, status: new, area: uop/stfc
