### ISSUE TITLE
Error caused by deleting proposal

### ISSUE THREAD

**Issue by voduguwa** [UserOfficeProject/user-office-project-issue-tracker#902] opened 2023-08-04 11:17 UTC
### What is the problem and why is it a problem
Errors showing in the application monitoring logs in the proposal backend when attempting to delete a proposal.

#### Associated errors: 

Error handling PROPOSAL_DELETED with handler 3:
`{"exception":{"name":"error","message":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *; - insert or update on table \"proposal_events\" violates foreign key constraint \"proposal_events_proposal_id_fkey\"","stack":"error: insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *; - insert or update on table \"proposal_events\" violates foreign key constraint \"proposal_events_proposal_id_fkey\"\n    at Parser.parseErrorMessage (/home/node/app/node_modules/pg-protocol/dist/parser.js:287:98)\n    at Parser.handlePacket (/home/node/app/node_modules/pg-protocol/dist/parser.js:126:29)\n    at Parser.parse (/home/node/app/node_modules/pg-protocol/dist/parser.js:39:38)\n    at TLSSocket.<anonymous> (/home/node/app/node_modules/pg-protocol/dist/index.js:11:42)\n    at TLSSocket.emit (node:events:513:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)"}}
`

QUERY ERROR:
`{"message":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *; - insert or update on table \"proposal_events\" violates foreign key constraint \"proposal_events_proposal_id_fkey\"","error":{"length":302,"name":"error","severity":"ERROR","code":"23503","detail":"Key (proposal_pk)=(16201) is not present in table \"proposals\".","schema":"public","table":"proposal_events","constraint":"proposal_events_proposal_id_fkey","file":"ri_triggers.c","line":"2783","routine":"ri_ReportViolation"},"obj":{"__knexUid":"__knexUid1210","__knexTxId":"__knexUid1210","method":"raw","sql":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *;","bindings":[true,16201],"options":{},"__knexQueryUid":"uZIRZPrDItJrtx7UjDQVf"},"QueryName":"insert into \"proposal_events\" (\"proposal_deleted\", \"proposal_pk\") values ($1, $2) ON CONFLICT (proposal_pk)\n        DO UPDATE SET\n        proposal_deleted = true\n        RETURNING *;"}`

### Steps to reproduce (if it's a bug).
As a user, draft a proposal: 
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108725376/20092baf-60cd-46a6-a03a-a57263548fc0)

Then delete the proposal and these errors will appear in the logs:
![image](https://github.com/UserOfficeProject/user-office-project-issue-tracker/assets/108725376/48b51c95-c97e-4efd-8026-07b524285be1)

**NOTE:** Proposals can still be deleted despite these errors showing up in the logs.

**Comment by simonfernandes** [comment] 2024-04-23 10:40
Duplicate of https://github.com/UserOfficeProject/issue-tracker/issues/928

**Closed as not planned by simonfernandes** 2024-04-23 10:40 UTC
Labels: area: uop/stfc
