### ISSUE TITLE
Keep FAP Review Assignments Table Loaded

### ISSUE THREAD

**Issue by Scott-James-Hurley** [UserOfficeProject/user-office-project-issue-tracker#1076] opened 2024-05-17 13:45 UTC
Reported by user to support inbox 16.05.24

When assigning FAP members to review proposals, users switch between the "MEMBERS" and "PROPOSAL AND ASSIGNMENTS" tabs to check how many reviews members have assigned to them whilst doing the assignments. They would like it if the the table showing review assignments in the "PROPOSAL AND ASSIGNMENTS" tab didn't have to load every time they switched tabs as it takes time to load the table and they lose their place.

This issue affect any users how assign FAP reviews and resolving it would make their workflow easier.

**Comment by TCMeldrum** [comment] 2024-07-09 15:39
Could we instead/as well show the number of assigned proposals in the PROPOSAL AND ASSIGNMENTS page somehow?

**Comment by joshhdawes** [comment] 2024-07-23 09:02
Could be closed by #1124?

**Comment by TCMeldrum** [comment] 2024-10-01 11:32
I'm not really to sure what the root issue is. I think they while they are assigning a proposal then switching tabs to look at the list of reviewers then switching back and losing their place. The only information that I can see that they are looking for is the proposal counts so I was wondering if I could add the proposal counts to the selection box as I think that would be easier than trying to keep there place on the assignment page.

**Comment by TCMeldrum** [comment] 2024-10-01 14:10
@Cat-Lucifer Do you think adding proposal count to the reviewer assignment would fix this? Or is there a use case I haven't considered? 
![image](https://github.com/user-attachments/assets/d8c2c843-97b5-41d1-9be2-69cc6ef7da90)

**Comment by Cat-Lucifer** [comment] 2024-10-01 15:08
@TCMeldrum  If the issue is that they are just checking the number of assigned reviews per reviewer, then I think this will work.  Does this window show all listed reviewers, as they may also check the numbers of assigned reviews across a few / all reviewers to look at the balance of proposals each has.

**Comment by TCMeldrum** [comment] 2024-10-01 15:22
Yeah it would show all reviewers. @Scott-James-Hurley do you remember who reported this so we can work out what they are asking for?

**Comment by TCMeldrum** [comment] 2024-10-08 11:53
From the support request it came in on:
"Minor annoyance is that when I navigate away to check the number of proposals on each reviewer I then have to reload the whole list when I come back which takes a few seconds and then page back to where I was."

So I think if we add the proposal counts to the proposals and assignments page that should resolve this issue hopefully.

**Closed as completed** 2024-10-14 11:56 UTC
Labels: origin: project, type: ux, area: uop/stfc/reviews-allocations
