### ISSUE TITLE
Demo the new proposal submission software for ISIS Rapid

### ISSUE THREAD

**Issue by sukhsingh2525** [UserOfficeProject/user-office-project-issue-tracker#582] opened 2022-05-27 14:33 UTC
We will be doing a demo at the ISIS rapid demo at the next IDG meeting which is likely to be 17th June. 

If this is not doable then we will need to organise another meeting for the  demo and request Philip for the mailing list.

**Comment by TickleThePanda** [comment] 2022-06-06 12:57
Closing as duplicate of https://github.com/UserOfficeProject/user-office-project-issue-tracker/issues/323

**Closed by TickleThePanda** 2022-06-06 12:57 UTC
Labels: type: process, area: uop/stfc
